### ISSUE TITLE
Navbar troubles

### ISSUE THREAD

**Issue by Ultragamer135** [UsernameNotAvalible/CollabOS#10]
Whenever i make a new page, i need to edit the navbar on every page! i need a way to edit the navbar on every page! does anyone have  any ideas to edit the navbar on every page at once?

**Comment by isakube** [comment]
if i'm not wrong, you could theoretically be able to make that a seperate html doc and then where you would put the stuff for the navbar on the pages, you could refer to the html doc (navbar.html ill call it) for the navigation bar and it could show up like that idk
this may not be possible but you could try it
