### ISSUE TITLE
ew block coding

### ISSUE THREAD

**Issue by ghost** [UsernameNotAvalible/CollabOS#21]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
assembly

**Describe alternatives you've considered**
no

**Additional context**
block coding bad

**Comment by isakube** [comment]
I never out-right say this without any prior interaction with someone, but fuck off.

**Comment by ghost** [comment]
toxic scratch user wt f???

**Comment by isakube** [comment]
> toxic scratch user wt f???

yes
