### ISSUE TITLE
Website branch is 10 commits behind main branch

### ISSUE THREAD

**Issue by Ultragamer135** [UsernameNotAvalible/CollabOS#9]
This is kind of a note to self, but... i need the website branch to be the same as the main branch!

**Comment by prokube** [comment]
What is the main branch and what is the site branch? docs contains the html, but what's the "main branch" called?

**Comment by isakube** [comment]
nvm i figured it out i think, i'll fix later
this is the web branch, right?: https://github.com/UsernameNotAvalible/UsernameNotAvalible.github.io
